stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-backend-job:       # This job runs in the build stage, which runs first.
  stage: build
  image: maven:3.8.4-openjdk-17
  script:
    - cd BackEnd/digitalbooking/
    - mvn clean package
    - echo "Compile complete."
  artifacts:
    paths:
      - BackEnd/digitalbooking/target/digitalbooking-0.0.1-SNAPSHOT.jar

build-frontend-job:
  stage: build
  script:
    - echo "Build finished"
      
unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running unit tests... This will take about 0 seconds."
    - echo "Code coverage is 90%"

deploy-backend-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - echo "$CI_PEM_FILE" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - echo "Deploying application to dev..."
    - echo "$CI_PEM_FILE" > key.pem
    - chmod 400 key.pem
    - scp -o StrictHostKeyChecking=no -i key.pem -r "$CI_PROJECT_DIR"/FrontEnd/digitalbooking/dist/* ubuntu@18.119.121.193:/home/ubuntu/gitlab/frontend/
    - scp -o StrictHostKeyChecking=no -i key.pem "$CI_PROJECT_DIR"/BackEnd/digitalbooking/target/digitalbooking-0.0.1-SNAPSHOT.jar ec2-user@3.138.189.133:/home/ec2-user/gitlab/digitalbooking.jar
    - ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@3.138.189.133 "sudo chmod +x deploy.sh && ./deploy.sh"
    - ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@18.119.121.193 "sudo chmod +x deploy.sh && ./deploy.sh"
    - echo "Application successfully deployed. Wait a few minutes while it starts on the server."
  only: 
    - dev
    - main

deploy-frontend-job:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set default.region $AWS_DEFAULT_REGION
    - aws s3 sync FrontEnd/digitalbooking/dist/ s3://dh-g8-front

  only:
    - dev
    - main