stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  image: maven:3.8.4-openjdk-17
  script:
    - cd BackEnd/digitalbooking/
    - mvn clean package
    - echo "Compile complete."
  artifacts:
    paths:
      - BackEnd/digitalbooking/target/digitalbooking-0.0.1-SNAPSHOT.jar

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running unit tests... This will take about 0 seconds."
    - echo "Code coverage is 90%"

deploy-dev:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - echo "$CI_PEM_FILE" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - echo "Deploying application to dev..."
    - echo "$CI_PEM_FILE" > key.pem
    - chmod 400 key.pem
    - scp -o StrictHostKeyChecking=no -i key.pem "$CI_PROJECT_DIR"/BackEnd/digitalbooking/target/digitalbooking-0.0.1-SNAPSHOT.jar ec2-user@ec2-18-218-175-122.us-east-2.compute.amazonaws.com:/home/ec2-user/gitlab/digitalbooking.jar
    - ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@ec2-18-218-175-122.us-east-2.compute.amazonaws.com "chmod +x deploy.sh && ./deploy.sh"
    - echo "Application successfully deployed. Wait a few minutes while it starts on the server."
  only: 
    - dev
